language: python
python:
        "3.6"
# command to install dependencies
install:
        - pip install lxml nbformat nbconvert IPython zmq ipywidgets
        - python setup.py develop
        - python build.py --clean --download
# command to run tests
script:
        pytest
