language: python
python:
        "3.6"
# command to install dependencies
install:
        - pip install lxml nbformat nbconvert IPython zmq
        - python setup.py develop --user
        - python setup.py install
        - python build.py --clean --download
# command to run tests
script:
        pytest
